#!/usr/bin/env python3
"""Create a Lazyreader project from canonical Markdown."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path


SKILL_ROOT = Path(__file__).resolve().parents[1]
TEMPLATE = SKILL_ROOT / "assets" / "reader-template"


def yaml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def ensure_frontmatter(markdown: str, fallback_title: str | None) -> tuple[str, str]:
    frontmatter = re.match(r"^---\n(?P<body>[\s\S]*?)\n---\n?", markdown)
    if frontmatter:
        title_match = re.search(r"^title:\s*[\"']?(.*?)[\"']?\s*$", frontmatter.group("body"), re.MULTILINE)
        if title_match and title_match.group(1).strip():
            return markdown, title_match.group(1).strip()
        if not fallback_title:
            heading = re.search(r"^#\s+(.+)$", markdown[frontmatter.end() :], re.MULTILINE)
            fallback_title = heading.group(1).strip() if heading else None
        if not fallback_title:
            raise ValueError("Markdown frontmatter has no title; pass --title")
        insertion = f"title: {yaml_string(fallback_title)}\n"
        start = frontmatter.start("body")
        return markdown[:start] + insertion + markdown[start:], fallback_title

    heading = re.search(r"^#\s+(.+)$", markdown, re.MULTILINE)
    title = fallback_title or (heading.group(1).strip() if heading else None)
    if not title:
        raise ValueError("Markdown has no title or H1; pass --title")
    metadata = (
        "---\n"
        f"title: {yaml_string(title)}\n"
        'author: ""\n'
        'site: ""\n'
        'source: ""\n'
        'description: ""\n'
        'published: ""\n'
        "---\n\n"
    )
    return metadata + markdown.lstrip(), title


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--markdown", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--port", type=int, default=4242)
    parser.add_argument("--title")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    if not 1 <= args.port <= 65535:
        raise ValueError("--port must be between 1 and 65535")
    if args.output.exists():
        if not args.force:
            raise FileExistsError(f"Output already exists: {args.output}")
        shutil.rmtree(args.output)

    markdown, title = ensure_frontmatter(args.markdown.read_text(encoding="utf-8"), args.title)
    shutil.copytree(TEMPLATE, args.output)
    (args.output / "content" / "article.md").write_text(markdown.rstrip() + "\n", encoding="utf-8")

    for relative in ("package.json", "README.md"):
        path = args.output / relative
        path.write_text(path.read_text().replace("__LAZYREADER_PORT__", str(args.port)))

    (args.output / "public" / "llms.txt").write_text(
        f"# {title}\n\nPrivate synchronized listening reader generated by Lazyreader.\n",
        encoding="utf-8",
    )
    print(f"Created {title!r} reader at {args.output} on port {args.port}")


if __name__ == "__main__":
    main()

